package main

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	awsdynamodb "github.com/aws/aws-cdk-go/awscdk/v2/awsdynamodb"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"
)

// Table names are pinned constants (not autogenerated by CDK) so the
// NixOS infra repo can wire them into /etc/kowloon/kowloon.env
// without having to read CloudFormation outputs on every deploy.
// Renaming a table is a manual, careful operation — a bump here would
// require creating the new table, dual-writing, backfilling, then
// dropping the old.
const (
	EmbeddingCacheTableName = "KowloonEmbeddingCache"
	IdempotencyTableName    = "KowloonIdempotency"
)

type KowloonStackProps struct {
	awscdk.StackProps
}

// NewKowloonStack provisions the two DynamoDB tables Kowloon uses for
// persistent caching + idempotency. Both tables:
//
//   - are pay-per-request (usage is bursty and small; no benefit from
//     provisioned capacity)
//   - have point-in-time recovery on (35-day continuous backup) — the
//     cost is negligible and it protects against a bad model swap
//     that would otherwise poison the cache
//   - use TTL on expires_at so stale entries auto-clean without a
//     cleanup Lambda
//   - are set to RETAIN on removal so `cdk destroy` cannot orphan the
//     data; deleting the tables is a deliberate, out-of-band action
func NewKowloonStack(scope constructs.Construct, id string, props *KowloonStackProps) awscdk.Stack {
	var sprops awscdk.StackProps
	if props != nil {
		sprops = props.StackProps
	}
	stack := awscdk.NewStack(scope, jsii.String(id), &sprops)

	embedCache := awsdynamodb.NewTable(stack, jsii.String("EmbeddingCache"), &awsdynamodb.TableProps{
		TableName: jsii.String(EmbeddingCacheTableName),
		PartitionKey: &awsdynamodb.Attribute{
			Name: jsii.String("cache_key"),
			Type: awsdynamodb.AttributeType_STRING,
		},
		BillingMode: awsdynamodb.BillingMode_PAY_PER_REQUEST,
		PointInTimeRecoverySpecification: &awsdynamodb.PointInTimeRecoverySpecification{
			PointInTimeRecoveryEnabled: jsii.Bool(true),
		},
		TimeToLiveAttribute: jsii.String("expires_at"),
		RemovalPolicy:       awscdk.RemovalPolicy_RETAIN,
	})

	idempotency := awsdynamodb.NewTable(stack, jsii.String("Idempotency"), &awsdynamodb.TableProps{
		TableName: jsii.String(IdempotencyTableName),
		PartitionKey: &awsdynamodb.Attribute{
			Name: jsii.String("idempotency_key"),
			Type: awsdynamodb.AttributeType_STRING,
		},
		BillingMode: awsdynamodb.BillingMode_PAY_PER_REQUEST,
		PointInTimeRecoverySpecification: &awsdynamodb.PointInTimeRecoverySpecification{
			PointInTimeRecoveryEnabled: jsii.Bool(true),
		},
		TimeToLiveAttribute: jsii.String("expires_at"),
		RemovalPolicy:       awscdk.RemovalPolicy_RETAIN,
	})

	// Outputs for the NixOS infra repo. Table names are already
	// constant, but exporting them as CFN outputs means the ARNs
	// (which do include the account/region) are addressable
	// programmatically for IAM policy construction on the NixOS
	// side.
	awscdk.NewCfnOutput(stack, jsii.String("EmbeddingCacheTableName"), &awscdk.CfnOutputProps{
		Value:      embedCache.TableName(),
		ExportName: jsii.String("KowloonEmbeddingCacheTableName"),
	})
	awscdk.NewCfnOutput(stack, jsii.String("EmbeddingCacheTableArn"), &awscdk.CfnOutputProps{
		Value:      embedCache.TableArn(),
		ExportName: jsii.String("KowloonEmbeddingCacheTableArn"),
	})
	awscdk.NewCfnOutput(stack, jsii.String("IdempotencyTableName"), &awscdk.CfnOutputProps{
		Value:      idempotency.TableName(),
		ExportName: jsii.String("KowloonIdempotencyTableName"),
	})
	awscdk.NewCfnOutput(stack, jsii.String("IdempotencyTableArn"), &awscdk.CfnOutputProps{
		Value:      idempotency.TableArn(),
		ExportName: jsii.String("KowloonIdempotencyTableArn"),
	})

	return stack
}
